config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "sessions/new"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/my_demand", to: "demands#my_demand"
    get "/dashboard", to: "admin#dashboard"

    resources :users, except: %i(index destroy)
    resources :demands
    resources :teach_offers

    namespace :admin do
      resources :users
      resources :demands
      resources :teach_offers
    end
  end
end

app/models/demand.rb
class Demand < ApplicationRecord
  belongs_to :user
  has_many :teach_offers

  validates :subject, :level, :fee, presence: true, length: {maximum: 50}
  validates :note, presence: true, length: {maximum: 200}
  validates :amount_student, :time_per_session, numericality: true
  enum status: {notfound: 0, found: 1}
  enum status_admin: {pending: 0, approved: 1, unapproved: 2}
end

app/controllers/admin/demands_controller.rb
class Admin::DemandsController < AdminController
  before_action :find_demand, except: :index

  def index
    @demands = if params[:search]
      Demand.joins(:user).where('subject LIKE ? OR users.name LIKE ? OR users.phone LIKE ?', "%#{params[:search]}% ", "%#{params[:search]}%", "%#{params[:search]}%").order("created_at DESC").page(params[:page]).per 20
    else
      Demand.order("created_at DESC").page(params[:page]).per 20
    end

  end

  def edit
    respond_to :js
  end

  def update
    if @demand.update! status_admin: params[:status_admin]
      flash[:success] = "Cập nhật thành công"
    else
      flash[:danger] = "Cập nhật thất bại"
    end
    redirect_to admin_demands_path
  end

  def destroy
    if @demand.destroy
      flash[:success] = "Xóa nhu cầu thành công"
    else
      flash.now[:danger] = "Xóa nhu cầu không thành công"
    end
    redirect_to admin_demands_path
  end

  private

  def find_demand
    @demand = Demand.find_by id: params[:id]
    return if @demand

    flash[:danger] = "Không tồn tại nhu cầu"
    redirect_to root_url
  end

  def demand_params
    params.require(:demand).permit(:user_id, :subject, :level, :amount_student, :time_per_session, :fee, :note, :address, :status, :status_admin)
  end
end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  before_action :logged_in_user, except: :index
  before_action :find_my_demand, only: %i(show destroy)
  def new
    @demand = Demand.new
  end

  def index
    @demands = if params[:search]
      Demand.where('address LIKE ? OR subject LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").order("created_at DESC").page(params[:page]).per 10
    else
      Demand.order("created_at DESC").page(params[:page]).per 10
    end
  end

  def my_demand
    @my_demands = current_user.demands.order("created_at DESC")
  end

  def create
    @demand = current_user.demands.new demand_params
    if @demand.save
      flash[:success] = "Tạo nhu cầu thành công"
      redirect_to demand_path @demand
    else
      render :new
    end
  end

  def show
  end

  def destroy
    if @demand.destroy
      respond_to :js
    else
      flash.now[:danger] = t "delete_borrowed_details_fail"
      redirect_to demands_path
    end
  end

  private

  def demand_params
    params.require(:demand).permit(:user_id, :subject, :level, :amount_student, :time_per_session, :fee, :note, :address, :status)
  end

  def find_my_demand
    @demand = current_user.demands.find_by id: params[:id]
    return if @demand

    flash[:danger] = "Không tồn tại nhu cầu"
    redirect_to root_url
  end
end

app/helpers/admin/demands_helper.rb
module Admin::DemandsHelper
end

app/views/admin/demands/_button_demand.html.erb
<% if @demand.pending? %>
  <%= link_to admin_demand_path(@demand, {status_admin: "approved"}), class: "btn btn-success", method: :patch do %>
    Phê duyệt
  <% end %>
  <%= link_to admin_demand_path(@demand, {status_admin: "unapproved"}), class: "btn btn-danger", method: :patch do %>
    Không phê duyệt
  <% end %>
<% elsif @demand.approved? %>
  <%= link_to admin_demand_path(@demand, {status_admin: "unapproved"}), class: "btn btn-danger", method: :patch do %>
    Không phê duyệt
  <% end %>
<% else %>
  <%= link_to admin_demand_path(@demand, {status_admin: "approved"}), class: "btn btn-success", method: :patch do %>
    Phê duyệt
  <% end %>
<% end %>

app/views/admin/demands/_demand.html.erb
<tr>
  <td><%= demand.user.name %></td>
  <td><%= demand.subject %></td>
  <td><%= demand.level %></td>
  <td><%= demand.user.phone %></td>
  <td>
    <% if demand.pending?%>
      <p class="status-pending">Đang chờ phê duyệt</p>
    <% elsif demand.approved? %>
      <p class="status-approved">Đã phê duyệt</p>
    <% else %>
      <p class="status-unapproved">Không phê duyệt</p>
    <% end %>
  </td>
  <td>
    <span>
      <%= link_to edit_admin_demand_path(demand), {remote: true, data:{toggle: "modal"}, data: {target: "#modal-window"}, class: "book-btn"} do %>
      <i class="fa fa-edit"></i>
      <% end %>
    </span>
    <span>
      <%= link_to admin_demand_path(demand), method: :delete, data: { confirm: "Bạn có chắc muốn xóa nhu cầu này?" }, class: "book-btn" do %>
      <i class="fa fa-trash"></i>
      <% end %>
    </span>
  </td>
</tr>

app/views/admin/demands/_edit.html.erb
<div class="modal-body">
  <%= render "show" %>
</div>
<div class="modal-footer">
  <%= render "button_demand" %>
</div>

app/views/admin/demands/_form_demand.html.erb
<%= form_for [:admin, @demand] do |f| %>
  <%= f.label "Môn học (Subject)", class: "required" %>
  <%= f.text_field :subject, class: "form-control", placeholder: "Toán" %>

  <%= f.label "Trình độ (Level)", class: "required" %>
  <%= f.text_field :level, class: "form-control", placeholder: "Lớp 5" %>

  <%= f.label "Số lượng người học (Amount student)", class: "required" %>
  <%= f.text_field :amount_student, class: "form-control", placeholder: "1, 2, ..." %>

  <%= f.label "Thời lượng học (Time per session)", class: "required" %>
  <%= f.text_field :time_per_session, class: "form-control", placeholder: "2h/buổi"  %>

  <%= f.label "Học phí (Fee)", class: "required" %>
  <%= f.text_field :fee, class: "form-control", placeholder: "200.000/buổi" %>

  <%= f.label "Địa chỉ:", class: "required" %>
  <%= f.text_field :address, class: "form-control", placeholder: "Đường Minh Khai, Hoàng Mai, Hà Nội" %>

  <%= f.label "Ghi chú (Note)", class: "required" %>
  <%= f.text_area :note, class: "form-control", placeholder: "Cần gia sư nữ, kinh nghiệm, học sinh mất tập trung,..." %>
  <%= f.submit "Đăng ký nhu cầu", class: "btn btn-primary" %>
<% end %>

app/views/admin/demands/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <div class="modal-title" id="myModalLabel" style="margin-left: -37rem;"">
    <h2 style="font-weight: bold;"> Nhu cầu</h2>
    <h4><%= @demand.user.name %></h4>
  </div>
</div>
<div class="modal-body">
  <td>Người đăng ký: <%= @demand.user.name %></td>
  <hr>
  <td>Mỗn học: <%= @demand.subject %></td>
  <hr>
  <td>Trình độ: <%= @demand.level %></td>
  <hr>
  <td>Số điện thoại:<%= @demand.user.phone %></td>
  <hr>
  <td>Số lượng học sinh: <%= @demand.amount_student %></td>
  <hr>
  <td>Phí nhận lớp: <%= @demand.fee %></td>
  <hr>
  <td>Thời lượng học 1 buổi: <%= @demand.time_per_session%>h/buổi</td>
  <hr>
  <td>Ghi chú: <%= @demand.note %></td>

</div>

app/views/admin/demands/edit.js.erb
$('#modal-window').find('.modal-content').html('<%= j render 'edit' %>');
$('#modal-window').modal();

app/views/admin/demands/index.html.erb
<% provide :title, "Quản lý nhu cầu" %>
<h2 style="
    text-align: center;
    font-size: 31px;
    text-transform: uppercase;
    font-weight: bold;
">Quản lý nhu cầu</h2>
<div class="row">
  <div class="col-sm-4 col-sm-push-8">
    <%= form_tag(admin_demands_path, method: :get) do %>
    <div class="col-sm-8">
      <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2" %>
    </div>
    <div class="col-sm-4">
      <%= submit_tag 'Search', class: "btn btn-outline-success my-2 my-sm-0" %>
    </div>
    <% end %>
  </div>
</div>
<div class="container-user">
  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">STT</th>
        <th scope="col">Người đăng nhu cầu</th>
        <th scope="col">Môn học</th>
        <th scope="col">Trình độ</th>
        <th scope="col">Số điện thoại</th>
        <th scope="col">Trạng thái</th>
        <th scope="col">Quản lý</th>

      </tr>
    </thead>
    <tbody>
      <%= render @demands %>
    </tbody>
  </table>
  <%= paginate @demands%>

</div>
<div id="modal-window" class="modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/admin/demands/show.js.erb
$('#modal-window').find('.modal-content').html('<%= j render 'show' %>');
$('#modal-window').modal();