config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "sessions/new"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/my_demand", to: "demands#my_demand"
    get "/dashboard", to: "admin#dashboard"

    resources :users, except: %i(index destroy)
    resources :demands
    resources :teach_offers

    namespace :admin do
      resources :users
      resources :demands
      resources :teach_offers
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  has_many :demands, dependent: :destroy
  has_many :teach_offers, dependent: :restrict_with_exception

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { maximum: 50 }, presence: true
  validates :birth, presence: true
  validates :address, length: { maximum: 200 }, presence: true
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX }
  validates :phone, presence: true
  validates :level, length: { maximum: 200 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  enum role: {user: 1, admin:2}

  has_secure_password

  class << self
# Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
# Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  include UserAction

  def index
    @users = if params[:search]
      @users = User.where('name LIKE ? OR phone LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").order("created_at DESC").page(params[:page]).per 20
    else
      @users = User.order("created_at DESC").page(params[:page]).per 20
    end
  end

  def show
    @user = User.find_by id: params[:id]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @user = User.find_by id: params[:id]
    begin
      @user.destroy!
      flash[:success] = "Xóa người dùng thành công"
    rescue
      flash[:danger] = "Không thể xóa do người dùng có đăng ký nhu cầu"
    ensure
      redirect_to admin_users_path
    end
  end
end

app/controllers/concerns/user_action.rb
module UserAction
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_user, only: [:edit, :update]
    before_action :correct_user , only: [:edit, :update]
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find_by id: params[:id]
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Đăng nhập thành công"
      redirect_to login_path
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:success] = "Cập nhật thành công"
      redirect_to current_user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone, :birth, :address, :password,
      :password_confirmation, :level)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel"><%= @user.name %></h4>
</div>
<div class="modal-body">
  <b>Họ tên: </b><%= @user.name %>
  <hr>
  <b>Email: </b><%= @user.email %>
  <hr>
  <b>Số điện thoại: </b><%= @user.phone %>
  <hr>
  <b>Ngày sinh: </b><%= @user.birth %>
  <hr>
  <b>Nghề nghiệp: </b><%= @user.level %>
  <hr>
  <b>Địa chỉ: </b><%= @user.address %>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.birth %></td>
  <td><%= user.email %></td>
  <td><%= user.phone %></td>
  <td><%= user.level %></td>
  <td>
    <span>
      <%= link_to admin_user_path(user), {remote: true, data:{toggle: "modal"}, data: {target: "#modal-window"}, class: "book-btn"} do %>
      <i class="fa fa-eye"></i>
      <% end %>
    </span>
    <span>
      <%= link_to admin_user_path(user), method: :delete, data: { confirm: "Bạn có chắc muốn xóa người dùng này?" }, class: "book-btn" do %>
      <i class="fa fa-trash"></i>
      <% end %>
    </span>
  </td>
</tr>

app/views/admin/users/index.html.erb
<% provide :title, "Quản lý người dùng" %>
<h2 style="
    text-align: center;
    font-size: 31px;
    text-transform: uppercase;
    font-weight: bold;
">Quản lý người dùng</h2>
<div class="row">
  <div class="col-sm-4 col-sm-push-8">
    <%= form_tag(admin_users_path, method: :get) do %>
    <div class="col-sm-8">
      <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2" %>
    </div>
    <div class="col-sm-4">
      <%= submit_tag 'Search', class: "btn btn-outline-success my-2 my-sm-0" %>
    </div>
    <% end %>
  </div>
</div>
<div class="container-user">
  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">STT</th>
        <th scope="col">Họ tên</th>
        <th scope="col">Ngày sinh</th>
        <th scope="col">Email</th>
        <th scope="col">Số điện thoại</th>
        <th scope="col">Nghệ nghiệp</th>
        <th scope="col">Quản lý</th>

      </tr>
    </thead>
    <tbody>
      <%= render @users %>
    </tbody>
  </table>
  <%= paginate @users%>
</div>
<div id="modal-window" class="modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/admin/users/show.js.erb
$('#modal-window').find('.modal-content').html('<%= j render 'show' %>');
$('#modal-window').modal();