config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "sessions/new"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/my_demand", to: "demands#my_demand"
    get "/dashboard", to: "admin#dashboard"

    resources :users, except: %i(index destroy)
    resources :demands
    resources :teach_offers

    namespace :admin do
      resources :users
      resources :demands
      resources :teach_offers
    end
  end
end

app/models/teach_offer.rb
class TeachOffer < ApplicationRecord
  belongs_to :user
  belongs_to :demand

  enum status: { pending: 0, approved: 1, unapproved: 2 }
end

app/controllers/admin/teach_offers_controller.rb
class Admin::TeachOffersController < AdminController
  before_action :find_teach_offer, only: %i(show update destroy)

  def index
    if params[:status].present?
      @teach_offers = TeachOffer.order("created_at DESC").where(status: params[:status]).page(params[:page]).per 20
    else
      @teach_offers = TeachOffer.order("created_at DESC").page(params[:page]).per 20
    end
  end

  def show
    respond_to :js
  end

  def destroy
    if @teach_offer.destroy
      flash[:success] = "Xóa thành công"
    else
      flash[:danger] = "Xóa không thành công"
    end
    redirect_to admin_teach_offers_path

  end

  def update
    if @teach_offer.update! status: params[:status]
      flash[:success] = "Cập nhật thành công!"
    else
      flash[:danger] = "Cập nhật không thành công!"
    end
    redirect_to admin_teach_offers_path
    return unless params[:status] == "approved"

    @teach_offer.demand.update! status: 1
  end

  private

  def find_teach_offer
    @teach_offer = TeachOffer.find_by id: params[:id]
    return if @teach_offer

    flash[:danger] = "Không tìm thấy đề nghị dạy nào!"
    redirect_to admin_teach_offers_path
  end
end

app/controllers/teach_offers_controller.rb
class TeachOffersController < ApplicationController
  before_action :load_demand, only: :create
  before_action :logged_in_user
  def index
    @teach_offers = current_user.teach_offers.order("created_at DESC").page(params[:page]).per 10
  end

  def create
    @teach_offer = current_user.teach_offers.find_by demand_id: @chosen_demand.id
    if @teach_offer
      flash[:danger] = "Bạn đã đề nghị dạy trước đó !"
    else
      current_user.teach_offers.create demand_id: @chosen_demand.id
      flash[:success] = "Đề nghị dạy thành công, trung tâm sẽ liên hệ bạn trong vòng 24h"
    end
    redirect_to teach_offers_path
  end

  private

  def load_demand
    @chosen_demand = Demand.find_by id: params[:demand_id]
    return if @chosen_demand

    flash[:danger] = "Not done"
    redirect_to root_url
  end

  def find_chosen_demand

    return if @teach_offer

    flash[:danger] = "not found"
    redirect_to root_url
  end
end

app/helpers/admin/teach_offers_helper.rb
module Admin::TeachOffersHelper
end

app/helpers/teach_offers_helper.rb
module TeachOffersHelper
end

app/views/admin/teach_offers/_button_teach_offer.html.erb
<% if @teach_offer.pending? %>
    <%= link_to admin_teach_offer_path(@teach_offer, {status: "approved"}), class: "btn btn-success", method: :patch do %>
      Phê duyệt
    <% end %>
    <%= link_to admin_teach_offer_path(@teach_offer, {status: "unapproved"}), class: "btn btn-danger", method: :patch do %>
      Không phê duyệt
    <% end %>
  <% elsif @teach_offer.approved? %>
    <%= link_to admin_teach_offer_path(@teach_offer, {status: "unapproved"}), class: "btn btn-danger", method: :patch do %>
      Không phê duyệt
    <% end %>
  <% else %>
    <%= link_to admin_teach_offer_path(@teach_offer, {status: "approved"}), class: "btn btn-success", method: :patch do %>
      Phê duyệt
    <% end %>
  <% end %>

app/views/admin/teach_offers/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel" style="font-size: 16px; font-weight: bold;
">Thông tin nhu cầu</h4>
</div>
<div class="modal-body">
  <aside>
    <td>Người đăng ký: <%= @teach_offer.demand.user.name %></td>
    <hr>
    <td>Mỗn học: <%= @teach_offer.demand.subject %></td>
    <hr>
    <td>Trình độ: <%= @teach_offer.demand.level %></td>
    <hr>
    <td>Số điện thoại:<%= @teach_offer.demand.user.phone %></td>
    <hr>
    <td>Số lượng học sinh: <%= @teach_offer.demand.amount_student %></td>
    <hr>
    <td>Phí nhận lớp: <%= @teach_offer.demand.fee %></td>
    <hr>
    <td>Thời lượng học 1 buổi: <%= @teach_offer.demand.time_per_session%>h/buổi</td>
    <hr>
    <td>Ghi chú: <%= @teach_offer.demand.note %></td>
  </aside>
  <hr>

  <aside>
    <h4 style="font-size: 16px; font-weight: bold; text-align: center;">
      Thông tin người đề nghị dạy
    </h4><hr>
    <b>Họ tên: </b><%= @teach_offer.user.name %>
    <hr>
    <b>Email: </b><%= @teach_offer.user.email %>
    <hr>
    <b>Số điện thoại: </b><%= @teach_offer.user.phone %>
    <hr>
    <b>Ngày sinh: </b><%= @teach_offer.user.birth %>
    <hr>
    <b>Nghề nghiệp: </b><%= @teach_offer.user.level %>
    <hr>
    <b>Địa chỉ: </b><%= @teach_offer.user.address %>
  </aside>
</div>

app/views/admin/teach_offers/_teach_offer.html.erb
<tr>
  <td><%= teach_offer.user.name %></td>
  <td><%= teach_offer.user.phone %></td>
  <td><%= teach_offer.demand.user.name %></td>
  <td><%= teach_offer.demand.user.phone %></td>
  <td style="width: 23rem; text-align: center;">
    <% if teach_offer.pending? %>
      <%= link_to admin_teach_offer_path(teach_offer, {status: "approved"}), class: "btn btn-success", method: :patch do %>
        Phê duyệt
      <% end %>
      <%= link_to admin_teach_offer_path(teach_offer, {status: "unapproved"}), class: "btn btn-danger", method: :patch do %>
        Không phê duyệt
      <% end %>
    <% elsif teach_offer.approved? %>
      <%= image_tag ("approved.png") , class: "approved"%>
    <% else %>
      <%= image_tag ("Cancel.png") , class: "approved"%>
    <% end %>
  </td>
  <td style="text-align: center;">
    <span>
      <%= link_to admin_teach_offer_path(teach_offer), {remote: true, data:{toggle: "modal"}, data: {target: "#modal-window"}, class: "book-btn"} do %>
      <i class="fa fa-eye"></i>
      <% end %>
    </span>
    <span>
      <%= link_to admin_teach_offer_path(teach_offer), method: :delete, class: "book-btn", data: {confirm: "Bạn có chắc muốn xóa?"} do %>
      <i class="fa fa-trash"></i>
      <% end %>
    </span>
  </td>
</tr>

app/views/admin/teach_offers/index.html.erb
<% provide :title, "Quản lý đề nghị dạy" %>
<h2 style="
    text-align: center;
    font-size: 31px;
    text-transform: uppercase;
    font-weight: bold;
">Quản lý đề nghị dạy</h2>
<div class="row">

  <div class="col-sm-4 col-sm-push-8">
    <%= form_tag admin_teach_offers_path, :method => 'get' do %>
      <%= select_tag(:status, options_for_select(TeachOffer.statuses.keys, params[:status]), onchange: 'this.form.submit();', class: "form-control custom-select" , include_blank: true )%>
    <% end %>
  </div>
</div>
<div class="container-user">
  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">STT</th>
        <th scope="col">Người đề nghị dạy</th>
        <th scope="col">Số điện thoại</th>
        <th scope="col">Người đăng nhu cầu</th>
        <th scope="col">Số điện thoại</th>
        <th scope="col">Trạng thái</th>
        <th scope="col"></th>

      </tr>
    </thead>
    <tbody>
      <%= render @teach_offers %>
    </tbody>
  </table>
  <%= paginate @teach_offers%>
</div>
<div id="modal-window" class="modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/admin/teach_offers/show.js.erb
$('#modal-window').find('.modal-content').html('<%= j render 'show' %>');
$('#modal-window').modal();