config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "sessions/new"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/my_demand", to: "demands#my_demand"
    get "/dashboard", to: "admin#dashboard"

    resources :users, except: %i(index destroy)
    resources :demands
    resources :teach_offers

    namespace :admin do
      resources :users
      resources :demands
      resources :teach_offers
    end
  end
end

app/views/layouts/_admin_header.html.erb
<div class="top">

</div>
<ul id="menu" class="menu">
  <li><%= link_to "Trang chủ", dashboard_path %></li>
  <li><%= link_to "Quản lý người dùng", admin_users_path %></li>
  <li><%= link_to "Quản lý nhu cầu", admin_demands_path %></li>
  <li><%= link_to "Quản lý đăng ký dạy", admin_teach_offers_path %></li>
  <li class="dropdown">
    <%= link_to  "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
    <%= current_user.name %>
    <% end %>
    <ul class="dropdown-menu">
      <li><%= link_to "Trang chủ", root_path %></li>
      <li>
        <%= link_to "Đăng xuất", logout_path, method: :delete %>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/_footer.html.erb
<div class="footer">

    <div class="l">
        <p><span style="font-size: 16px;"><strong>GIA SƯ BÁCH KHOA</strong></span><br> Địa chỉ: 376 Lê Hồng Phong, Phường 1, Quận 10<br> Email: giasubk247@gmail.com<br> Hotline: 0838300655 / 0916276271 / 0908018459</p>    </div>
    <div class="r">

<!-- <a href="http://ebiv.vn/c/trung-tam-gia-su-bach-khoa/wall" target = "_blank" title="Chỉ số tín nhiệm cá nhân đầu tiên tại Việt Nam"> <img src="images/logott.png" width ="138" height ="90" align ="left" /></a> -->

        <a href="#" title="Gia su bách khoa">Trang chủ</a>   |
        <a href="#" title="Khu vực dành cho phụ huynh">Dành cho phụ huynh</a>    |
        <a href="#" title="Lớp gia sư hiện có">Dành cho  gia sư</a>   |
        <a href="#" title="Tuyển dụng - Trung tâm Gia sư bách khoa">Tuyển dụng</a><br>
        Copyright 2010 Trung tâm <a href="#" title="Gia sư bách khoa">Gia sư Bách Khoa</a>.
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="top">

</div>
<ul id="menu" class="menu">
  <li><%= link_to "Trang chủ", root_url %></li>
  <li><%= link_to "Giới thiệu", about_path %></li>
  <li><%= link_to "Nhu cầu mới", demands_path %></li>
  <li><%= link_to "Đăng ký nhu cầu", new_demand_path %></li>
  <li><%= link_to "Liên hệ", contact_path %></li>
  <% if logged_in? %>
    <li class="dropdown">
      <%= link_to  "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
        <%= current_user.name %>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to "Thông tin cá nhân", current_user %></li>
        <li><%= link_to "Cài đặt", edit_user_path(current_user) %></li>
        <li><%= link_to "Nhu cầu đăng ký", my_demand_path %></li>
        <li><%= link_to "Đề nghị dạy", teach_offers_path %></li>
        <% if current_user.admin? %>
        <li><%= link_to "Quản lý trung tâm", dashboard_path %></li>
        <% end %>
        <li>
          <%= link_to "Đăng xuất", logout_path, method: :delete %>
        </li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to "Đăng nhập", login_path %></li>
    <li><%= link_to "Đăng Ký", signup_path %></li>
  <% end %>
</ul>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <div class="container content">
      <%= render "layouts/admin_header" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>

    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <div class="container content">
      <%= render "layouts/header" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>

    </div>
  </body>
</html>